apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  dev-config.json:
    '{
      "example.datasource.url": "jdbc:mysql://dev-endpoint/example",
      "example.datasource.username": "dev-root",
      "example.datasource.password": "dev-pass"
     }'