apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-config-map
  name: spring-config-map
spec:
  containers:
    - image: gcr.io/spring-config-map/reactive/latest:v1
      name: spring-config-map
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPRING_PROFILE
          value: dev
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: dev-config.json
  restartPolicy: Never