apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  port: 8080
  tenant: abc
  title: abc organization title
  contact: abc organization contact

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: extranalized-spring-configration
  name: extranalized-spring-configration
spec:
  containers:
    - image: gcr.io/externalized-properties/latest:v1
      name: extranalized-spring-configration
      imagePullPolicy: IfNotPresent
      env:
        - name: app.port
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key:  port
        - name: app.profile
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: tenant
        - name: organization.name
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: tenant
        - name: organization.title
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: title
        - name: organization.contact
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: contact
  restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: extranalized-spring-configration-service
spec:
  selector:
    app: extranalized-spring-configration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
