apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  tenant: abc
  title: abc organization title
  contact: abc organization contact

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-balancer-extranalized-spring-configration
  name: extranalized-spring-configration
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-extranalized-spring-configration
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-extranalized-spring-configration
    spec:
      containers:
        - image: gcr.io/externalized-properties/latest:v1
          name: extranalized-spring-configration
          imagePullPolicy: IfNotPresent
          env:
            - name: app.port
              value: "8080"
            - name: app.profile
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: tenant
            - name: organization.name
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: tenant
            - name: organization.title
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: title
            - name: organization.contact
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: contact


#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: extranalized-spring-configration-service
#spec:
#  selector:
#    app: extranalized-spring-configration
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
