apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  org: abc dev
  title: abc dev organization title
  contact: abc dev organization contact

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-extranalized-config
data:
  organization.name: abc extranalized dev
  organization.title: abc extranalized dev organization title
  organization.contact: abc extranalized dev organization contact

---
apiVersion: v1
kind: Secret
metadata:
  name: dev-extranalized-secret
type: Opaque
stringData:
  database.service: clear text default is base64 encoded strings.
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  database.username: devuser1
  database.password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-balancer-extranalized-spring-configration
  name: extranalized-spring-configration
spec:
  replicas: 1
  selector:
    matchLabels:
      name: load-balancer-extranalized-spring-configration
  template:
    metadata:
      labels:
        name: load-balancer-extranalized-spring-configration
    spec:
      containers:
        - image: gcr.io/externalized-properties/latest:v1
          name: extranalized-spring-configration
          ports:
            - containerPort: 9090
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "9090"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
#            - name: organization.name
#              valueFrom:
#                configMapKeyRef:
#                  name: spring-config
#                  key: org
#            - name: organization.title
#              valueFrom:
#                configMapKeyRef:
#                  name: spring-config
#                  key: title
#            - name: organization.contact
#              valueFrom:
#                configMapKeyRef:
#                  name: spring-config
#                  key: contact
          envFrom:
            - configMapRef:
                name: dev-extranalized-config
            - secretRef:
                name: dev-extranalized-secret


### create service with External IP address
# kubectl expose deployment extranalized-spring-configration --type=LoadBalancer  --name=extranalized-config-service --port=80 --target-port=9090

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: extranalized-spring-configration-service
#spec:
#  selector:
#    app: extranalized-spring-configration
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
