apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  org: abc dev
  title: abc dev organization title
  contact: abc dev organization contact

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-extranalized-config
data:
  org: abc extranalized dev
  title: abc extranalized dev organization title
  contact: abc extranalized dev organization contact

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-balancer-extranalized-spring-configration
  name: extranalized-spring-configration
spec:
  replicas: 1
  selector:
    matchLabels:
      name: load-balancer-extranalized-spring-configration
  template:
    metadata:
      labels:
        name: load-balancer-extranalized-spring-configration
    spec:
      containers:
        - image: gcr.io/externalized-properties/latest:v1
          name: extranalized-spring-configration
          ports:
            - containerPort: 9090
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "9090"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
#            - name: organization.name
#              valueFrom:
#                configMapKeyRef:
#                  name: spring-config
#                  key: org
#            - name: organization.title
#              valueFrom:
#                configMapKeyRef:
#                  name: spring-config
#                  key: title
#            - name: organization.contact
#              valueFrom:
#                configMapKeyRef:
#                  name: spring-config
#                  key: contact
          envFrom:
            - configMapRef:
                name: dev-extranalized-config

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: extranalized-spring-configration-service
#spec:
#  selector:
#    app: extranalized-spring-configration
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
